services:
  # paperless-ngx main service
  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless-ngx
    restart: unless-stopped
    env_file: 
      - ./paperless/.env
    depends_on:
      - postgres-paperless
      - redis
      - gotenberg
      - tika
    ports:
      - "8000:8000"
    volumes:
      - ./paperless/data:/usr/src/paperless/data
      - ./paperless/media:/usr/src/paperless/media
      - ./paperless/export:/usr/src/paperless/export
      - ./paperless/consume:/usr/src/paperless/consume
  
  # postgres database for paperless-ngx
  postgres-paperless:
    image: postgres:18
    restart: unless-stopped
    container_name: postgres-paperless
    env_file: 
      - ./postgres-paperless/.env
    volumes:
      - ./postgres-paperless/data:/var/lib/postgresql
  
  # redis database for paperless-ngx
  redis:
    image: docker.io/library/redis:8
    container_name: redis
    restart: unless-stopped
    env_file: 
      - ./redis/.env
    volumes:
      - ./redis/data:/data
  
  # gotenberg service that paperless uses for document conversion
  gotenberg:
    image: docker.io/gotenberg/gotenberg:8.25
    container_name: gotenberg
    env_file: 
      - ./gotenberg/.env
    restart: unless-stopped
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
  
  # tika service that paperless uses for document text extraction
  tika:
    image: docker.io/apache/tika:latest
    container_name: tika
    restart: unless-stopped
    env_file: ./tika/.env
  

    # open-webui service for LLM interaction
  open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: open-webui
    restart: unless-stopped
    env_file:
      - ./open-webui/.env
    depends_on:
      - ollama
    ports:
      - "3001:8080"
    volumes:
      - ./open-webui/data:/app/backend/data

  # ollama service for local LLMs
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    env_file:
      - ./ollama/.env
    volumes:
      - ./ollama/data/:/root/.ollama
      - ./ollama/models:/ollama-models
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  # paperless-ai service
  paperless-ai:
    image: clusterzx/paperless-ai:latest
    container_name: paperless-ai
    restart: unless-stopped
    depends_on:
      - ollama
      - paperless
    ports:
      - "3000:3000"
    env_file:
      - ./paperless-ai/.env
    volumes:
      - ./paperless-ai/data:/app/data
  

  # paperless-gpt service
  paperless-gpt:
    image: icereed/paperless-gpt:latest
    container_name: paperless-gpt
    restart: unless-stopped
    depends_on:
      - ollama
      - paperless
    ports:
      - "3002:8080"
    env_file:
      - ./paperless-gpt/.env
    volumes:
      - ./paperless-gpt/prompts:/app/prompts # Mount the prompts directory


  # optional but helpful log viewer
  dozzle:
    image: amir20/dozzle:latest
    restart: unless-stopped
    container_name: dozzle
    env_file: 
      - ./dozzle/.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dozzle/data:/data
    ports:
      - "8080:8080"

 # postgres database dedicated to n8n
  postgres-n8n:
    image: postgres:18
    restart: unless-stopped
    container_name: postgres-n8n
    env_file:
      - ./postgres-n8n/.env  
    volumes:
      - ./postgres-n8n/data:/var/lib/postgresql

  # n8n workflow automation service
  n8n:
    image: docker.io/n8nio/n8n:latest
    container_name: n8n
    user: root
    restart: unless-stopped
    ports:
      - "5678:5678"
    depends_on:
      - postgres-n8n
    env_file:
      - ./n8n/.env      
    volumes:
      - ./n8n/data:/home/node/.n8n

  # syncthing service
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: ubuntu-syncthing
    env_file:
      - ./syncthing/.env      
    volumes:
      - ./syncthing/config:/config # Where Syncthing stores its database
      - ./paperless/consume:/usr/src/paperless/consume
    ports:
      - 8384:8384      # Web UI port
      - 22000:22000/tcp # Data sync listening port (TCP)
      - 22000:22000/udp # Data sync listening port (UDP)
      - 21027:21027/udp # Local network discovery protocol
    restart: unless-stopped      
